config/routes.rb
Rails.application.routes.draw do
	match '/jushos/todofuken_select' => 'jushos#todofuken_select' , via: :get
  resources :jushos

  resources :shichosons

  resources :todofukens

end

app/models/jusho.rb
class Jusho < ActiveRecord::Base
  belongs_to :todofuken
  belongs_to :shichoson
end

app/models/shichoson.rb
class Shichoson < ActiveRecord::Base
  belongs_to :todofuken
end

app/models/todofuken.rb
class Todofuken < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jushos_controller.rb
class JushosController < ApplicationController
  before_action :set_jusho, only: [:show, :edit, :update, :destroy]
	protect_from_forgery except: :todofuken_select
  # GET /jushos
  # GET /jushos.json
  def index
    @jushos = Jusho.all
  end

  # GET /jushos/1
  # GET /jushos/1.json
  def show
  end

  # GET /jushos/new
  def new
    @jusho = Jusho.new
		@shichosons = [["都道府県を選択してください。", "0"]]
		    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jusho }
    end
  end
  # GET /jushos/todoufuken_select
  def todofuken_select
		@shichosons = Shichoson.where(todofuken_id: params[:todofuken_id])
		#@shichosons = Shichoson.all

	  respond_to do |format|
			#format.html {render html: @shichosons}
			format.json {render json: @shichosons}
		end
		
  end
  # GET /jushos/1/edit
  def edit
		@shichosons = @jusho.shichoson_id
  end

  # POST /jushos
  # POST /jushos.json
  def create
    @jusho = Jusho.new(jusho_params)

    respond_to do |format|
      if @jusho.save
        format.html { redirect_to @jusho, notice: 'Jusho was successfully created.' }
        format.json { render :show, status: :created, location: @jusho }
      else
        format.html { render :new }
        format.json { render json: @jusho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jushos/1
  # PATCH/PUT /jushos/1.json
  def update
    respond_to do |format|
      if @jusho.update(jusho_params)
        format.html { redirect_to @jusho, notice: 'Jusho was successfully updated.' }
        format.json { render :show, status: :ok, location: @jusho }
      else
        format.html { render :edit }
        format.json { render json: @jusho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jushos/1
  # DELETE /jushos/1.json
  def destroy
    @jusho.destroy
    respond_to do |format|
      format.html { redirect_to jushos_url, notice: 'Jusho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jusho
      @jusho = Jusho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jusho_params
      params.require(:jusho).permit(:todofuken_id, :shichoson_id, :sonotajusho)
    end
end

app/controllers/shichosons_controller.rb
class ShichosonsController < ApplicationController
  before_action :set_shichoson, only: [:show, :edit, :update, :destroy]

  # GET /shichosons
  # GET /shichosons.json
  def index
    @shichosons = Shichoson.all
  end

  # GET /shichosons/1
  # GET /shichosons/1.json
  def show
  end

  # GET /shichosons/new
  def new
    @shichoson = Shichoson.new
  end

  # GET /shichosons/1/edit
  def edit
  end

  # POST /shichosons
  # POST /shichosons.json
  def create
    @shichoson = Shichoson.new(shichoson_params)

    respond_to do |format|
      if @shichoson.save
        format.html { redirect_to @shichoson, notice: 'Shichoson was successfully created.' }
        format.json { render :show, status: :created, location: @shichoson }
      else
        format.html { render :new }
        format.json { render json: @shichoson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shichosons/1
  # PATCH/PUT /shichosons/1.json
  def update
    respond_to do |format|
      if @shichoson.update(shichoson_params)
        format.html { redirect_to @shichoson, notice: 'Shichoson was successfully updated.' }
        format.json { render :show, status: :ok, location: @shichoson }
      else
        format.html { render :edit }
        format.json { render json: @shichoson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shichosons/1
  # DELETE /shichosons/1.json
  def destroy
    @shichoson.destroy
    respond_to do |format|
      format.html { redirect_to shichosons_url, notice: 'Shichoson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shichoson
      @shichoson = Shichoson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shichoson_params
      params.require(:shichoson).permit(:todofuken_id, :name)
    end
end

app/controllers/todofukens_controller.rb
class TodofukensController < ApplicationController
  before_action :set_todofuken, only: [:show, :edit, :update, :destroy]

  # GET /todofukens
  # GET /todofukens.json
  def index
    @todofukens = Todofuken.all
  end

  # GET /todofukens/1
  # GET /todofukens/1.json
  def show
  end

  # GET /todofukens/new
  def new
    @todofuken = Todofuken.new
  end

  # GET /todofukens/1/edit
  def edit
  end

  # POST /todofukens
  # POST /todofukens.json
  def create
    @todofuken = Todofuken.new(todofuken_params)

    respond_to do |format|
      if @todofuken.save
        format.html { redirect_to @todofuken, notice: 'Todofuken was successfully created.' }
        format.json { render :show, status: :created, location: @todofuken }
      else
        format.html { render :new }
        format.json { render json: @todofuken.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todofukens/1
  # PATCH/PUT /todofukens/1.json
  def update
    respond_to do |format|
      if @todofuken.update(todofuken_params)
        format.html { redirect_to @todofuken, notice: 'Todofuken was successfully updated.' }
        format.json { render :show, status: :ok, location: @todofuken }
      else
        format.html { render :edit }
        format.json { render json: @todofuken.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todofukens/1
  # DELETE /todofukens/1.json
  def destroy
    @todofuken.destroy
    respond_to do |format|
      format.html { redirect_to todofukens_url, notice: 'Todofuken was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todofuken
      @todofuken = Todofuken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todofuken_params
      params.require(:todofuken).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jushos_helper.rb
module JushosHelper
end

app/helpers/shichosons_helper.rb
module ShichosonsHelper
end

app/helpers/todofukens_helper.rb
module TodofukensHelper
end

app/views/jushos/_form.html.erb
<%= form_for(@jusho) do |f| %>
  <% if @jusho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jusho.errors.count, "error") %> prohibited this jusho from being saved:</h2>

      <ul>
      <% @jusho.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todofuken %><br />
    <%= f.collection_select(:todofuken_id, Todofuken.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :shichoson %><br />
    <%= render 'todofuken_select', {:f => f} %>
  </div>
  <div class="field">
    <%= f.label :sonotajusho %><br />
    <%= f.text_field :sonotajusho %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jushos/_todofuken_select.html.erb
<%= f.select(:shichoson_id, @shichosons) %>

app/views/jushos/edit.html.erb
<h1>Editing jusho</h1>

<%= render 'form' %>

<%= link_to 'Show', @jusho %> |
<%= link_to 'Back', jushos_path %>

app/views/jushos/index.html.erb
<h1>Listing jushos</h1>

<table>
  <thead>
    <tr>
      <th>Todofuken</th>
      <th>Shichoson</th>
      <th>Sonotajusho</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jushos.each do |jusho| %>
      <tr>
				<td><%= jusho.todofuken.name %></td>
				<td><%= jusho.shichoson.name %></td>
        <td><%= jusho.sonotajusho %></td>
        <td><%= link_to 'Show', jusho %></td>
        <td><%= link_to 'Edit', edit_jusho_path(jusho) %></td>
        <td><%= link_to 'Destroy', jusho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jusho', new_jusho_path %>

app/views/jushos/new.html.erb
<h1>New jusho</h1>

<%= render 'form' %>

<%= link_to 'Back', jushos_path %>

app/views/jushos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todofuken:</strong>
	<%= @jusho.todofuken.name %>
</p>

<p>
  <strong>Shichoson:</strong>
	<%= @jusho.shichoson.name %>
</p>

<p>
  <strong>Sonotajusho:</strong>
  <%= @jusho.sonotajusho %>
</p>

<%= link_to 'Edit', edit_jusho_path(@jusho) %> |
<%= link_to 'Back', jushos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kobayan2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shichosons/_form.html.erb
<%= form_for(@shichoson) do |f| %>
  <% if @shichoson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shichoson.errors.count, "error") %> prohibited this shichoson from being saved:</h2>

      <ul>
      <% @shichoson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :todofuken_id %><br>
    <%= f.text_field :todofuken_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shichosons/edit.html.erb
<h1>Editing shichoson</h1>

<%= render 'form' %>

<%= link_to 'Show', @shichoson %> |
<%= link_to 'Back', shichosons_path %>

app/views/shichosons/index.html.erb
<h1>Listing shichosons</h1>

<table>
  <thead>
    <tr>
      <th>Todofuken</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shichosons.each do |shichoson| %>
      <tr>
        <td><%= shichoson.todofuken %></td>
        <td><%= shichoson.name %></td>
        <td><%= link_to 'Show', shichoson %></td>
        <td><%= link_to 'Edit', edit_shichoson_path(shichoson) %></td>
        <td><%= link_to 'Destroy', shichoson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shichoson', new_shichoson_path %>

app/views/shichosons/new.html.erb
<h1>New shichoson</h1>

<%= render 'form' %>

<%= link_to 'Back', shichosons_path %>

app/views/shichosons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todofuken:</strong>
  <%= @shichoson.todofuken %>
</p>

<p>
  <strong>Name:</strong>
  <%= @shichoson.name %>
</p>

<%= link_to 'Edit', edit_shichoson_path(@shichoson) %> |
<%= link_to 'Back', shichosons_path %>

app/views/todofukens/_form.html.erb
<%= form_for(@todofuken) do |f| %>
  <% if @todofuken.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todofuken.errors.count, "error") %> prohibited this todofuken from being saved:</h2>

      <ul>
      <% @todofuken.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todofukens/edit.html.erb
<h1>Editing todofuken</h1>

<%= render 'form' %>

<%= link_to 'Show', @todofuken %> |
<%= link_to 'Back', todofukens_path %>

app/views/todofukens/index.html.erb
<h1>Listing todofukens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todofukens.each do |todofuken| %>
      <tr>
        <td><%= todofuken.name %></td>
        <td><%= link_to 'Show', todofuken %></td>
        <td><%= link_to 'Edit', edit_todofuken_path(todofuken) %></td>
        <td><%= link_to 'Destroy', todofuken, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todofuken', new_todofuken_path %>

app/views/todofukens/new.html.erb
<h1>New todofuken</h1>

<%= render 'form' %>

<%= link_to 'Back', todofukens_path %>

app/views/todofukens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todofuken.name %>
</p>

<%= link_to 'Edit', edit_todofuken_path(@todofuken) %> |
<%= link_to 'Back', todofukens_path %>